sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t rrazooki/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rrazooki/docker-react npm run test -- --coverage